# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('contact', models.CharField(max_length=100, verbose_name='聯系地址')),
                ('content', models.TextField(verbose_name='留言內容')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-id'],
            },
        ),
    ]
