# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contact',
            new_name='address',
        ),
    ]
